### ISSUE TITLE
Issue Pulling Test Script Code w/Autograder

### ISSUE THREAD

**Issue by martmichals** [martmichals/ece_test_scripts#4]
Talked to someone that tried running the test scripts via FastX. Was able to replicate the error. Here is an image of the printout.
![error](https://user-images.githubusercontent.com/49954516/75807312-c1e20680-5d4a-11ea-80d7-4295bf726d6e.JPG)

**Comment by martmichals** [comment]
Found that line 43 of ece_test_scripts/autograder/ece220_autograde.sh causes the issue. Permission to fetch is denied.

![error2](https://user-images.githubusercontent.com/49954516/75808942-839a1680-5d4d-11ea-87ee-67d48eae0cea.JPG)

**Comment by CaptnSisko** [comment]
Fixed
